name: Build APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: cimg/android:2023.12
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
        
    - name: Install pip and Python dependencies
      run: |
        curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
        python3 get-pip.py
        python3 -m pip install buildozer cython
        
    - name: Build APK
      run: |
        export PATH=$PATH:$HOME/.local/bin
        buildozer android debug
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: bin/*.apk